server:
  port: 9595
spring:
  application:
    name: parking-paid
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
